### ISSUE TITLE
Add a built-in console process type

### ISSUE THREAD

**Issue by jkutner** [heroku/sbt-heroku#10]
The plugin should create a built-in process type for running `sbt console`. Currently, the `heroku run sbt console` command [as describe in this article](https://devcenter.heroku.com/articles/running-a-remote-sbt-console-for-a-scala-or-play-application) will not work.

**Comment by danielkza** [comment]
The SBT libraries are not included in the staged package, and neither is the SBT configuration from your project, unlike the traditional Heroku workflow. It's possible adding files manually can work, but you'd likely end up doing more work than simply using Heroku directly.

**Comment by jkutner** [comment]
Yea, that would be a pain. But it's also possible to start a non-sbt console for an app that is staged with sbt-native-packager 0.7.6 or newer. The resulting command would be a `heroku run console` that executed something like:

```
$ target/universal/stage/bin/<your-app> -main scala.tools.nsc.MainGenericRunner -usejavacp
```

**Comment by jkutner** [comment]
Added a branch for this:
https://github.com/heroku/sbt-heroku/tree/console
