### ISSUE TITLE
Include with_jmap and with_jstack scripts

### ISSUE THREAD

**Issue by jkutner** [heroku/sbt-heroku#11]
So it can be used like this:
https://devcenter.heroku.com/articles/java-memory-issues#generating-thread-dumps

**Comment by jkutner** [comment]
Fixed by upgrading to heroku-deploy 0.3.2

**Comment by liorhar** [comment]
@jkutner can you elaborate on the fix? how with_jmap should be used in conjunction with the sbt-heroku plugin?
I'm trying to prefix the default shell script generated by play with with_jmap but that doesn't work.
Is there any example I can use?

**Comment by jkutner** [comment]
@liorhar what version of sbt-heroku are you using? The latest (0.5.4) should work with the play sh script. Usage is the same as described here:
https://devcenter.heroku.com/articles/java-memory-issues#generating-heap-dumps-in-the-background

**Comment by liorhar** [comment]
right, it worked, I was using 0.5.1 thought it contained the fix.
thanks a lot

**Comment by jkutner** [comment]
I think 0.3.2 contained a partial fix that didn't work quite like the normal buildpack. let us know if you have issues with the newer versions.
