### ISSUE TITLE
Commit version

### ISSUE THREAD

**Issue by jmaynier** [heroku/sbt-heroku#12]
Since the slug is compiled locally then pushed, there is no git commit version displayed in the activity tab on heroku dashboard, which is usefull to know which version is deployed.
Is there a way to convey this information via the heroku deploy api ?

**Comment by jkutner** [comment]
I've added this in heroku-deploy: https://github.com/heroku/heroku-maven-plugin/commit/8adf1366922a3bed3a278cb40455e45b84e6670c

sbt-heroku will take up this version in the 0.3.3 release... probably in a day or two.

**Comment by jkutner** [comment]
Should be fixed now. Let us know if it's not working they way you expected.
