### ISSUE TITLE
Attempting to use deployHeroku with a play-scalajs project

### ISSUE THREAD

**Issue by Voltir** [heroku/sbt-heroku#14]
I am working with a fork of https://github.com/vmunier/play-with-scalajs-example, trying to add the heroku sbt plugin to help facilitate deployments.

I think the problem I am running into is that that project has a non-standard layout. I set herokuSkipSubProjects in Compile to false and then I run into the following error:

[sitejvm] $ deployHeroku
[trace] Stack trace suppressed: run last sitejvm/compile:deployHeroku for the full output.
[error] (sitejvm/compile:deployHeroku) java.io.FileNotFoundException: target/universal/stage/bin/sitejvm (No such file or directory)
[error] Total time: 0 s, completed Feb 16, 2015 3:27:46 PM

I think I want it to use sitejvm/target/universal/stage/bin/sitejvm, but it isnt clear how that path is being created.

EDIT: As a workaround: ln -s sitejvm/target/ . from the top level directory seems to work.

EDIT EDIT: Does not actually deploy though -- I get a myriad of errors depending on what I do, but it seems that the first problem happens when it tries to install OpenJDK (side question... installing OpenJDK where?) and I get the following error: 

[trace] Stack trace suppressed: run last sitejvm/compile:deployHeroku for the full output.
[error] (sitejvm/compile:deployHeroku) java.net.SocketException: Connection reset
[error] Total time: 341 s, completed Feb 16, 2015 4:01:49 PM

**Comment by jkutner** [comment]
First, try setting your web process type like this:

```scala
herokuProcessTypes in Compile := Map(
  "web" -> "sitejvm/target/universal/stage/bin/sitejvm"
)
```

But you may also need to explicitly include that dir. So add this:

```scala
herokuIncludePaths in Compile := Seq(
  "sitejvm/target/universal/stage"
)
```

If that doesn't work, trying logging into your app with `$ heroku run bash`, and inspect the slug with `ls` to see if you need to add any other directories to `herokuIncludePaths`.

If it still does not work after that, I will probably need to tweak the way sbt-heroku handles subprojects (there are seemingly infinite possible setups, and I have not yet accounted for all of them). I *have* prepared the internals such that you could include some subdirs and not others (but I haven't exposed that in the config. So I may need to finish that up in order for this to work.

Let us know what happens. I'm interested in this use case, so i will probably tinker with the [https://github.com/vmunier/play-with-scalajs-example](https://github.com/vmunier/play-with-scalajs-example) project tonight. But I want to make sure I cover your fork too.

Thanks for reporting this!

**Comment by Voltir** [comment]
Without the hardlink, I get the error java.io.FileNotFoundException: target/universal/stage/bin/sitejvm (No such file or directory)

If I add the hardlink, I get the following:
[error] (sitejvm/compile:deployHeroku) java.io.IOException: There was an error packaging the application for deployment.

Which on inspection, seems to have this root cause:

Caused by: java.nio.file.FileAlreadyExistsException: /home/nick/tests/stable-heroku-test/sitejvm/target/heroku/app/target/universal/stage/conf/application.conf

However, if I comment out herokuIncludePaths completely, it seems to progress further:

[sitejvm] $ deployHeroku
[info] ---> Packaging application...
[info]      - app: stable-test-sbt
[info]      - including: ./target/universal/stage/
[info]      - installing: OpenJDK 1.8

Which appears to hang for a few minutes then generates the connection timeout exception.

**Comment by jkutner** [comment]
The connection timeout must happen when downloading the JDK. It's about 60mb. Are you still getting that error? Do you have a slow connection?

**Comment by jkutner** [comment]
I was able to get the original project working. But I had to fix a bug in sbt-heroku, so you'll need to upgrade to 0.3.4.  You can see what I did in this Pull Request: https://github.com/vmunier/play-with-scalajs-example/pull/31

**Comment by Voltir** [comment]
Yay :)

Worked on my branch. This saves me a lot of grief due to compilation timeouts when trying to use git push heroku master... so thank you for the plugin.

**Comment by Voltir** [comment]
Ok, I have been using it for a more complex app and have run into an occasional problem:

```
[gametime-site] $ deployHeroku
[info] ---> Packaging application...
[info]      - app: stable-gametime
[info]      - including: ./target/universal/stage/
[info]      - installing: OpenJDK 1.8
[info] ---> Creating slug...
[info]      - file: ./target/heroku/slug.tgz
[info]      - size: 129MB
[info] ---> Uploading slug...
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
```

**Comment by jkutner** [comment]
You'll probably need to set the heap size for the sbt process a little larger. I use `SBT_OPTS="-Xms512M -Xmx1028M -Xss1M"` by default

**Comment by jkutner** [comment]
Closing this. But let me know if you have any further problems.
