### ISSUE TITLE
Error configuring

### ISSUE THREAD

**Issue by DiogoTavaresDeAlmeidaRibeiro** [heroku/sbt-heroku#15]
Sorry for the noob question.

I'm trying to configure sbt-heroku but keep getting this error in build.sbt:

    [info] Loading project definition from ...\project
    ....\build.sbt:11: error: not found: value herokuAppName
    herokuAppName in Compile := "appsho3-staging"
    ^
    [error] Type error in expression

My build.sbt

    import play.Project._
    
    name := "Appsho"
    
    version := "1.0-SNAPSHOT"
    
    libraryDependencies ++= Seq(
      cache
    )     
    
    herokuAppName in Compile := "appsho3-staging"
    
    play.Project.playJavaSettings
    
    lazy val root = project.in(file(".")).aggregate(common, internal, edu).dependsOn(common, internal, edu)
    
    lazy val common = project.in(file("modules/common"))
    
    lazy val internal = project.in(file("modules/internal")).dependsOn(common)
    
    lazy val edu = project.in(file("modules/edu")).dependsOn(common)

**Comment by jkutner** [comment]
Have you added `addSbtPlugin("com.heroku" % "sbt-heroku" % "0.3.4")` to your `project/plugins.sbt`?

**Comment by DiogoTavaresDeAlmeidaRibeiro** [comment]
Yes, my plugins.sbt:

    // Comment to get more information during initialization
    logLevel := Level.Warn
    
    // The Typesafe repository
    resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
    
    // Use the Play sbt plugin for Play projects
    addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.6")
    
    addSbtPlugin("com.heroku" % "sbt-heroku" % "0.3.4")

**Comment by jkutner** [comment]
What version of sbt are you using? You'll need 0.13.5 or higher

**Comment by DiogoTavaresDeAlmeidaRibeiro** [comment]
That was it! I was using sbt 0.13.0. 

Thanks for your help jkutner
