### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by DiogoTavaresDeAlmeidaRibeiro** [heroku/sbt-heroku#16]
Is it possible to show some kind of upload progress?

**Comment by jjstaats** [comment]
Would be nice. The upload does seem to sometimes take much longer than excepted. Maybe a simple time indication between steps so we get a better idea of how long each step can take?

**Comment by jjstaats** [comment]
I would like to add:
sbt-deploy-test(master)> deployHeroku
[info] ---> Packaging application...
[info]      - app: protected-river-****
[info]      - including: target/universal/stage/
[info]      - installing: OpenJDK 1.7
[info] ---> Creating slug...
[info]      - file: target/heroku/slug.tgz
[info]      - size: 102MB
[info] ---> Uploading slug...
[info]      - stack: cedar-14                                                                                                                                                                                                    
[info]      - process types: [web]
[info] ---> Releasing...
[info]      - version: 4
[success] Total time: 1277 s, completed 20-apr-2015 15:38:07

21 minutes for a deploy of an empty play project.

Just to be clean I think this is a great project and I would really like to using this for my production heroku apps.

**Comment by jkutner** [comment]
Are you deploying from the EU? I think the S3 repo that the slug is uploaded to is in the US -- even if your app is in the EU. I'm going to investigate how we can fix that.

**Comment by jjstaats** [comment]
My test app was in the US. I created another app in the EU. The upload time was just as long (about 20 minutes). 

It seems to be a problem with windows or intellij's terminal because if I deploy from an ubuntu vm (running in virtualbox) both US and EU takes only 3 minutes.

This seems to be a problem on my side and not really something of this project. 

So to not go off-topic: +1 the original feature request.

**Comment by jkutner** [comment]
@jjstaats thanks for the info. I have seen this same problem on Windows (both from the Terminal and from Eclipse). So I don't think it is Intellij. What version of the JDK are you using locally?

I've already started some work on this feature, so should be available in the near future.

**Comment by jjstaats** [comment]
@jkutner the project is linked to 1.7.0_51 (64bit) but the system default is 1.8.0_31 (64bit), not sure what parts of intellij (including the buildin terminal) is native and what runs on java.

**Comment by jkutner** [comment]
progress https://github.com/heroku/heroku-maven-plugin/commit/e3a454bbb5569555af02be06877ec34d0e8eb070

**Comment by jkutner** [comment]
fixed in 0.3.7
