### ISSUE TITLE
support for .jdk-overlay folder into the packaged jdk

### ISSUE THREAD

**Issue by ggmoriyon** [heroku/sbt-heroku#18]
First of all, thank you for your great effort. I find this sbt plugin very useful for using jenkins as the way to deploy into Heroku.

Sometimes, there is a need to extend the default jdk bundled in Heroku. For example, when requiring Java JCE in your project. 
Heroku enables the jdk customization mechanism to extend the bundled jdk as documented in https://devcenter.heroku.com/articles/customizing-the-jdk

I have created a sample project to show this: https://github.com/ggmoriyon/sbt-heroku-include-jdk-overlay-sample

To reproduce the current behavior:

* download sample project
* execute: heroku create
* modify build.sbt with the name of the heroku app
* execute: sbt stage deployHeroku
* check target/heroku/app folder: it contains both .jdk and .jdk-overlay, while the contents of .jdk-overlay should be included into the .jdk folder

**Comment by jkutner** [comment]
Yes, makes perfect sense, and should be easy to do. It will increase parity with the buildpack, which is a good thing.

I'll should be able to knock this out very soon, and have a release early next week.

**Comment by jkutner** [comment]
This will be available in version 0.3.6 (or 0.4.0 because I might bump in this release). I expect to deploy it on Friday.

**Comment by ggmoriyon** [comment]
that's great news Joe! thanks!
