### ISSUE TITLE
sbt-heroku adds jQuery to the classpath

### ISSUE THREAD

**Issue by vmunier** [heroku/sbt-heroku#24]
Hello,

It looks like `sbt-heroku` adds jQuery to the classpath.

I came across the issue while using Scala.js with jQuery.

How to reproduce:
- clone the scala-js example repo https://github.com/sjrd/scala-js-example-app
- add `"be.doeraene" %%% "scalajs-jquery" % "0.8.0"` to the `libraryDependencies` https://github.com/sjrd/scala-js-example-app/blob/53d88a4f774a623414d8603825b190ca50942121/build.sbt#L16-L19
- everything works fine when executing `sbt fastOptJS`
- But if I now add the sbt-heroku plugin, `addSbtPlugin("com.heroku" % "sbt-heroku" % "0.5.3")` to `project/build.sbt` and execute `sbt fastOptJS`, I get the error:
```
[error] (compile:scalaJSPreLinkClasspath) org.scalajs.core.tools.classpath.JSLibResolveException: Some references to JS libraries could not be resolved:
[error] - Ambiguous reference to a JS library: jquery.js
[error]   Possible paths found on the classpath:
[error]   - scala/tools/nsc/doc/html/resource/lib/jquery.js
[error]   - META-INF/resources/webjars/jquery/2.1.3/jquery.js
[error]   originating from: root:compile
```

`Ambiguous reference to a JS library: jquery.js` because there are two jquery.js, one coming from the `scalajs-jquery` library (as expected), another one coming from `sbt-heroku`.

Do you know why sbt-heroku adds jQuery to the classpath?

**Comment by jkutner** [comment]
I'm not sure what's putting that on the path, but it must be a dependency. Here's the graph:

```
[info]   +-com.heroku.sdk:heroku-deploy:0.5.3
[info]     +-com.fasterxml.jackson.core:jackson-core:2.3.0
[info]     +-com.fasterxml.jackson.core:jackson-databind:2.3.0
[info]     | +-com.fasterxml.jackson.core:jackson-annotations:2.3.0
[info]     | +-com.fasterxml.jackson.core:jackson-core:2.3.0
[info]     |
[info]     +-commons-io:commons-io:2.4
[info]     +-org.apache.commons:commons-compress:1.5
[info]     | +-org.tukaani:xz:1.2
[info]     |
[info]     +-org.apache.commons:commons-lang3:3.3.2
[info]     +-org.apache.httpcomponents:httpclient:4.4
[info]     | +-commons-codec:commons-codec:1.9
[info]     | +-commons-logging:commons-logging:1.2
[info]     | +-org.apache.httpcomponents:httpcore:4.4
[info]     |
[info]     +-org.eclipse.jgit:org.eclipse.jgit:3.6.2.201501210735-r
[info]       +-com.googlecode.javaewah:JavaEWAH:0.7.9
[info]       +-com.jcraft:jsch:0.1.50
[info]       +-org.apache.httpcomponents:httpclient:4.1.3 (evicted by: 4.4)
[info]       +-org.apache.httpcomponents:httpclient:4.4
[info]         +-commons-codec:commons-codec:1.9
[info]         +-commons-logging:commons-logging:1.2
[info]         +-org.apache.httpcomponents:httpcore:4.4
```

Mostly likely culprit would be jackson i guess. I'll investigate.

**Comment by jkutner** [comment]
The problem seems to be [here in HerokuPlugin](https://github.com/heroku/sbt-heroku/blob/master/src/main/scala/com/heroku/sbt/HerokuPlugin.scala#L86):

```scala
libraryDependencies <+= scalaVersion("org.scala-lang" % "scala-compiler" % _ ),
```

I'm pulling that in to enable the Scala console on Heroku. It would be pretty easy to exclude, but i'm not sure of the best way and it would prevent the console from working on Heroku.

**Comment by jkutner** [comment]
So this is really annoying. Why does the scala-compiler jar include docs??

```
$ jar tf scala-compiler-2.11.7.jar | grep jquery
scala/tools/nsc/doc/html/resource/lib/jquery-ui.js
scala/tools/nsc/doc/html/resource/lib/jquery.js
scala/tools/nsc/doc/html/resource/lib/jquery.layout.js
```

**Comment by vmunier** [comment]
:+1: Thank you.

**Comment by jkutner** [comment]
@vmunier i just need to run CI and few integration tests and i'll push out 0.5.3.1 with the fix. thanks for reporting!

**Comment by jkutner** [comment]
https://bintray.com/heroku/sbt-plugins/sbt-heroku/0.5.3.1/view
