### ISSUE TITLE
Is it possible for sbt-heroku to work with "Deploy to Heroku" button?

### ISSUE THREAD

**Issue by eponvert** [heroku/sbt-heroku#25]
From what I'm seeing in https://devcenter.heroku.com/articles/heroku-button, it looks like `app.json` expects there to be a source repository, I'm not seeing JVM-style binary deployment supported.

**Comment by jkutner** [comment]
No, sbt-heroku and heroku-button use two distinct mechanisms for deployment. It is possible to configure an application be deployed in both ways without conflict. But they still use different mechanisms.

What are you hoping to accomplish? Maybe I can offer some other suggestions.

**Comment by eponvert** [comment]
I'm about to open source an application, which I've configured to be relatively easily deployed to Heroku via sbt-heroku. Just wondering if the deploy button were easily enough added given that set-up. I can probably configure it to deploy via git commit + Procfile as an alternative.

Thanks! Question answered :metal:

**Comment by jkutner** [comment]
Cool! please share a link to the project when it's ready. I'd be happy to help with the heroku-button part.
