### ISSUE TITLE
Ability to override app name using system property

### ISSUE THREAD

**Issue by hipnoizz** [heroku/sbt-heroku#28]
The primary use case is deploying to Heroku using CI servers. I want to be able to easily duplicate an existing CI job (or maybe parameterize it) and deploy under whatever Heroku app name without a need to change `build.sbt`. I know that I can put something like `herokuAppName in Compile := sys.props("heroku-app-name")` in `build.sbt` but then I need to put it in every project.

Heroku Maven plugin (https://github.com/heroku/heroku-maven-plugin) supports this scenario using  `heroku.appName` system property.

**Comment by jkutner** [comment]
Fixed by 41c41945ea8d1bdacd83d982d1f8fca6bdbaddbd. This will be available in 1.0.1, which should be released later today.
