### ISSUE TITLE
Error 422 while trying to deploy

### ISSUE THREAD

**Issue by paulovictorv** [heroku/sbt-heroku#33]
Hello, this is rather a confusing problem.

So earlier today I've successfully released my app. After deploying, I found a bug and needed to deploy a hotfix. However, since the hotfix I'm not able to deploy. The plugin is throwing 422 http error while trying to deploy. The hotfix itself didn't touch with the build process, it was a code change and all my tests are passing. It uploads fine, but when it tries to actually deploy the app, it screams the 422 error.

I've tried to rollback the app to a previous version to see if the deploy worked, and I've also tried to deploy to a new app I created. No luck.

For the life of me, I can't think of what is causing the problem. Can you please point me to the right direction?

Thanks

**Comment by jkutner** [comment]
@paulovictorv can you should me the output of the build? Also, can you put `logLevel := Level.Debug` in your `build.sbt` and run again to see if there is any other meaningful output? Thanks.

**Comment by paulovictorv** [comment]
@jkutner Sure.

There goes the [diagnostics.log](http://pastebin.com/JXqRG4bH).

Here the output with [Level.Debug](http://pastebin.com/pBE9BeA8).

Thanks!

**Comment by jkutner** [comment]
I can actually reproduce the problem. hang tight. thanks

**Comment by jkutner** [comment]
@paulovictorv The problem was a change to the Heroku API, which has now been rolled back. Please try again, and I'll be happy to reopen this if you still have problems.
