### ISSUE TITLE
support sbt 1.0

### ISSUE THREAD

**Issue by xuwei-k** [heroku/sbt-heroku#38]

**Comment by jkutner** [comment]
I don't believe [sbt-native-packager](https://github.com/sbt/sbt-native-packager) has added support for 1.0 yet, and I think I'm going to need to follow on that.

**Comment by jkutner** [comment]
Whelp, guess it's time to start thinking about this: https://twitter.com/muuki88/status/895020700418936833

**Comment by jkutner** [comment]
Not able to get very far on this:

```
sbt-heroku/build.sbt:11: error: not found: value crossSbtVersions
crossSbtVersions := Vector("0.13.16", "1.0.0")
^
[error] Type error in expression
```

I'm following the pattern of how `crossSbtVersions` is used in `sbt-release` and `sbt-native-packager`, and I've [read the limited documentation](http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt+0.13.16). I'm using 0.13.6.

@xuwei-k do you know what I'm missing?

**Comment by xuwei-k** [comment]
The `crossSbtVersions`  key available since sbt 0.13.**16**, not 0.13.**6**

**Comment by jkutner** [comment]
@xuwei-k thanks 😜

**Comment by jkutner** [comment]
working in branch [sbt1](https://github.com/heroku/sbt-heroku/tree/sbt1)
