### ISSUE TITLE
syntax error: operand expected (error token is ".")

### ISSUE THREAD

**Issue by francisdb** [heroku/sbt-heroku#42]
Sorry for reporting this here but there is no other way to reach out to the scala team (support ticket) as I have a free heroku app

scala sbt builds on jdk11 hit this bug

https://github.com/paulp/sbt-extras/issues/212
see also https://github.com/sbt/sbt/issues/5342

So I guess Heroku should update it's scala pipeline to use the new sbt-extras?

**Comment by Malax** [comment]
Hello @francisdb!

Thank you for researching this and bringing this to our attention! This will be fixed soon, see https://github.com/heroku/heroku-buildpack-scala/pull/144

**Comment by francisdb** [comment]
Great, thanks

**Comment by Malax** [comment]
This has been fixed and deployed for the `heroku/scala` buildpack.
