### ISSUE TITLE
Upgrade to New Stack

### ISSUE THREAD

**Issue by neilchaudhuri** [heroku/sbt-heroku#45]
I need to upgrade my Play Framework (Scala) app to the cedar-18 stack, but I use sbt-heroku to deploy. I have not seen any documentation regarding how this can be accomplished. Can you point me to some?

Also, is it possible to reuse addons with the new stack? Or do I need to provision a new database instance and migrate the data there myself?

**Comment by Malax** [comment]
You can either use [Herokus CLI](https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack#upgrading-an-app) or [the dashboard](https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack#upgrading-via-dashboard) to upgrade to a new stack. `sbt-heroku` itself cannot upgrade your stack.

Your addons are independent of the stack and should continue working. You don't need to provision a new database instance for example.

**Comment by neilchaudhuri** [comment]
Glad to hear. Thanks.
