### ISSUE TITLE
Support multiple environments

### ISSUE THREAD

**Issue by jkutner** [heroku/sbt-heroku#6]
Currently, the only way to deploy to multiple environments (i.e. dev, test and prod) is through system properties, like this:

```
herokuAppName in Compile := (if (sys.props("appName") == null) "myapp" else sys.props("appName"))
```
and then running

```
sbt -DappName=myapp-test stage deployHeroku
```
However, it would nice to have a more natural approach that easily allows for multiple environments to be configured. I would love suggestions on how this might look.

**Comment by danielkza** [comment]
Using sbt-git you can get something pretty nice based on which branch is currently checked out. I use something like this:

plugins.sbt
```scala
resolvers ++= Seq(
  Resolver.typesafeRepo("releases"),
  "jgit-repo" at "http://download.eclipse.org/jgit/maven",
  Resolver.url("heroku-sbt-plugin-releases", url("https://dl.bintray.com/heroku/sbt-plugins/"))
    (Resolver.ivyStylePatterns),
)

addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.6.4")

addSbtPlugin("com.heroku" % "sbt-heroku" % "0.3.0")
```

build.sbt
```scala
import com.typesafe.sbt.SbtGit._

// ...

herokuAppName in Compile := Map(
  "testing"    -> "myapp-testing",
  "staging"    -> "myapp-staging",
  "production" -> "myapp"
).getOrElse(git.gitCurrentBranch.value, "")

herokuJdkVersion in Compile := "1.8"

showCurrentGitBranch
```

**Comment by jkutner** [comment]
@danielkza nice! i really like that solution. I'm going to add it to the docs, and close this ticket. Thanks!
